export const AUTHENTICATE = "AUTHENTICATE";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";

export const SET_LOADING = "SET_LOADING";
export const SET_LOADING_BLEETS = "SET_LOADING_BLEETS";

export const GET_BLEETS = "GET_BLEETS";
export const GET_BLEET_BY_ID = "GET_BLEET_BY_ID";

export const UPDATE_AOP = "UPDATE_AOP";
export const GET_AOP = "GET_AOP";

export const GET_911_CALLS = "GET_911_CALLS";
export const END_911_CALL = "END_911_CALL";
export const UPDATE_911_CALL = "UPDATE_911_CALL";

export const GET_CURRENT_OFFICER_STATUS = "GET_CURRENT_OFFICER_STATUS";
export const GET_MY_OFFICERS = "GET_MY_OFFICERS";
export const DELETE_OFFICER_BY_ID = "DELETE_OFFICER_BY_ID";
export const CREATE_OFFICER = "CREATE_OFFICER";
export const CREATE_OFFICER_ERROR = "CREATE_OFFICER_ERROR";

export const SET_STATUS = "SET_STATUS";
export const GET_BOLOS = "GET_BOLOS";

export const CREATE_WARRANT = "CREATE_WARRANT";
export const CREATE_WARRANT_ERROR = "CREATE_WARRANT_ERROR";

export const GET_DEPARTMENTS = "GET_DEPARTMENTS";

export const GET_ACTIVE_UNITS = "GET_ACTIVE_UNITS";

export const CREATE_TOW_CALL = "CREATE_TOW_CALL";
export const GET_TOW_CALLS = "GET_TOW_CALLS";
export const END_TOW_CALL = "END_TOW_CALL";

export const SET_MESSAGE = "SET_MESSAGE";

export const GET_TRUCK_LOGS = "GET_TRUCK_LOGS";
export const CREATE_TRUCK_LOG = "CREATE_TRUCK_LOG";
export const DELETE_TRUCK_LOG = "DELETE_TRUCK_LOG";
