export const AUTHENTICATE = "AUTHENTICATE";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";

export const SET_LOADING = "SET_LOADING";
export const SET_LOADING_BLEETS = "SET_LOADING_BLEETS";

export const GET_BLEETS = "GET_BLEETS";
export const GET_BLEET_BY_ID = "GET_BLEET_BY_ID";
export const CREATE_BLEET = "CREATE_BLEET";
export const CREATE_BLEET_ERROR = "CREATE_BLEET_ERROR";
export const UPDATE_BLEET = "UPDATE_BLEET";
export const UPDATE_BLEET_ERROR = "UPDATE_BLEET_ERROR";

export const UPDATE_AOP = "UPDATE_AOP";
export const GET_AOP = "GET_AOP";

export const GET_911_CALLS = "GET_911_CALLS";
export const END_911_CALL = "END_911_CALL";
export const UPDATE_911_CALL = "UPDATE_911_CALL";
export const CREATE_911_CALL = "CREATE_911_CALL";

export const GET_CURRENT_OFFICER_STATUS = "GET_CURRENT_OFFICER_STATUS";
export const GET_MY_OFFICERS = "GET_MY_OFFICERS";
export const DELETE_OFFICER_BY_ID = "DELETE_OFFICER_BY_ID";
export const CREATE_OFFICER = "CREATE_OFFICER";
export const CREATE_OFFICER_ERROR = "CREATE_OFFICER_ERROR";

export const CREATE_WRITTEN_WARNING = "CREATE_WRITTEN_WARNING";
export const CREATE_WRITTEN_WARNING_ERROR = "CREATE_WRITTEN_WARNING_ERROR";
export const CREATE_TICKET = "CREATE_TICKET";
export const CREATE_TICKET_ERROR = "CREATE_TICKET_ERROR";
export const CREATE_ARREST_REPORT = "CREATE_ARREST_REPORT";
export const CREATE_ARREST_REPORT_ERROR = "CREATE_ARREST_REPORT_ERROR";

export const GET_CURRENT_EMS_STATUS = "GET_CURRENT_EMS_STATUS";
export const GET_MY_EMS_FD = "GET_MY_EMS_FD";
export const SET_EMS_STATUS = "SET_EMS_STATUS";
export const CREATE_EMS_FD_DEPUTY = "CREATE_EMS_FD_DEPUTY";
export const CREATE_EMS_FD_DEPUTY_ERROR = "CREATE_EMS_FD_DEPUTY_ERROR";
export const DELETE_EMS_DEPUTY = "DELETE_EMS_DEPUTY";
export const SEARCH_MEDICAL_RECORD = "SEARCH_MEDICAL_RECORD";

export const SET_STATUS = "SET_STATUS";

export const GET_BOLOS = "GET_BOLOS";
export const CREATE_BOLO = "CREATE_BOLO";
export const CREATE_BOLO_ERROR = "CREATE_BOLO_ERROR";
export const DELETE_BOLO = "DELETE_BOLO";

export const CREATE_WARRANT = "CREATE_WARRANT";
export const CREATE_WARRANT_ERROR = "CREATE_WARRANT_ERROR";

export const GET_ACTIVE_UNITS = "GET_ACTIVE_UNITS";

export const CREATE_TOW_CALL = "CREATE_TOW_CALL";
export const GET_TOW_CALLS = "GET_TOW_CALLS";
export const END_TOW_CALL = "END_TOW_CALL";

export const SET_MESSAGE = "SET_MESSAGE";

export const GET_TRUCK_LOGS = "GET_TRUCK_LOGS";
export const CREATE_TRUCK_LOG = "CREATE_TRUCK_LOG";
export const CREATE_TRUCK_LOG_ERROR = "CREATE_TRUCK_LOG_ERROR";
export const DELETE_TRUCK_LOG = "DELETE_TRUCK_LOG";

export const GET_CITIZENS = "GET_CITIZENS";
export const GET_CITIZEN_BY_ID = "GET_CITIZEN_BY_ID";
export const CREATE_CITIZEN = "CREATE_CITIZEN";
export const CREATE_CITIZEN_ERROR = "CREATE_CITIZEN_ERROR";
export const DELETE_CITIZEN = "DELETE_CITIZEN";
export const UPDATE_LICENSES = "UPDATE_LICENSES";
export const GET_VEHICLE_BY_ID = "GET_VEHICLE_BY_ID";
export const GET_ALL_CITIZENS = "GET_ALL_CITIZENS";
export const TRANSFER_VEHICLE = "TRANSFER_VEHICLE";
export const TRANSFER_VEHICLE_ERROR = "TRANSFER_VEHICLE_ERROR";

export const GET_COMPANY_DATA = "GET_COMPANY_DATA";
export const GET_COMPANY_BY_ID = "GET_COMPANY_BY_ID";
export const JOIN_COMPANY = "JOIN_COMPANY";
export const JOIN_COMPANY_ERROR = "JOIN_COMPANY_ERROR";
export const CREATE_COMPANY = "CREATE_COMPANY";
export const CREATE_COMPANY_ERROR = "CREATE_COMPANY_ERROR";
export const CREATE_COMPANY_POST = "CREATE_COMPANY_POST";
export const CREATE_COMPANY_POST_ERROR = "CREATE_COMPANY_POST_ERROR";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const UPDATE_COMPANY_ERROR = "UPDATE_COMPANY_ERROR";

export const GET_MEDICAL_RECORDS = "GET_MEDICAL_RECORDS";
export const CREATE_MEDICAL_RECORD = "CREATE_MEDICAL_RECORD";
export const CREATE_MEDICAL_RECORD_ERROR = "CREATE_MEDICAL_RECORD_ERROR";
export const DELETE_MEDICAL_RECORD = "DELETE_MEDICAL_RECORD";

export const REGISTER_WEAPON = "REGISTER_WEAPON";
export const REGISTER_WEAPON_ERROR = "REGISTER_WEAPON_ERROR";
export const GET_REGISTERED_WEAPONS = "GET_REGISTERED_WEAPONS";
export const DELETE_REGISTERED_WEAPON = "DELETE_REGISTERED_WEAPON";

export const REGISTER_VEHICLE = "REGISTER_VEHICLE";
export const REGISTER_VEHICLE_ERROR = "REGISTER_VEHICLE_ERROR";
export const GET_REGISTERED_VEHICLES = "GET_REGISTERED_VEHICLES";
export const DELETE_REGISTERED_VEHICLE = "DELETE_REGISTERED_VEHICLE";

export const PLATE_SEARCH = "PLATE_SEARCH";
export const NAME_SEARCH = "NAME_SEARCH";
export const ADDRESS_SEARCH = "ADDRESS_SEARCH";
export const WEAPON_SEARCH = "WEAPON_SEARCH";

/* admin*/
export const GET_COMPANIES = "GET_COMPANIES";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const GET_MEMBERS = "GET_MEMBERS";
export const GET_MEMBER_BY_ID = "GET_MEMBER_BY_ID";
export const UPDATE_MEMBER_PERMS = "UPDATE_MEMBER_PERMS";
export const BAN_MEMBER = "BAN_MEMBER";
export const UN_BAN_MEMBER = "UN_BAN_MEMBER";
export const ACCEPT_USER = "ACCEPT_USER";
export const DECLINE_USER = "DECLINE_USER";
export const UPDATE_CAD_SETTINGS = "UPDATE_CAD_SETTINGS";
export const GET_CAD_INFO = "GET_CAD_INFO";

/* All values */
export const DELETE_VALUE = "DELETE_VALUE";
export const ADD_VALUE = "ADD_VALUE";
export const ADD_VALUE_ERROR = "ADD_VALUE_ERROR";
export const GET_VALUE_BY_ID = "GET_VALUE_BY_ID";
export const UPDATE_VALUE_BY_ID = "UPDATE_VALUE_BY_ID";
export const UPDATE_VALUE_BY_ID_ERROR = "UPDATE_VALUE_BY_ID_ERROR";

export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const GET_ADMIN_DEPARTMENTS = "GET_ADMIN_DEPARTMENTS";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";

export const GET_GENDERS = "GET_GENDERS";
export const UPDATE_GENDER = "UPDATE_GENDER";

export const GET_ETHNICITIES = "GET_ETHNICITIES";
export const UPDATE_ETHNICITY = "UPDATE_ETHNICITY";

export const GET_WEAPONS = "GET_WEAPONS";
export const UPDATE_WEAPON = "UPDATE_WEAPON";

export const GET_VEHICLES = "GET_VEHICLES";
export const UPDATE_VEHICLE = "UPDATE_VEHICLE";

export const GET_LEGAL_STATUSES = "GET_LEGAL_STATUSES";
export const UPDATE_LEGAL_STATUS = "UPDATE_LEGAL_STATUS";
