export const AUTHENTICATE = "AUTHENTICATE";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";

export const SET_LOADING = "SET_LOADING";
export const SET_LOADING_BLEETS = "SET_LOADING_BLEETS";

export const GET_BLEETS = "GET_BLEETS";
export const GET_BLEET_BY_ID = "GET_BLEET_BY_ID";

export const UPDATE_AOP = "UPDATE_AOP";
export const GET_AOP = "GET_AOP";

export const GET_911_CALLS = "GET_911_CALLS";
export const END_911_CALL = "END_911_CALL";
export const UPDATE_911_CALL = "UPDATE_911_CALL";
export const CREATE_911_CALL = "CREATE_911_CALL";

export const GET_CURRENT_OFFICER_STATUS = "GET_CURRENT_OFFICER_STATUS";
export const GET_MY_OFFICERS = "GET_MY_OFFICERS";
export const DELETE_OFFICER_BY_ID = "DELETE_OFFICER_BY_ID";
export const CREATE_OFFICER = "CREATE_OFFICER";
export const CREATE_OFFICER_ERROR = "CREATE_OFFICER_ERROR";

export const GET_CURRENT_EMS_STATUS = "GET_CURRENT_EMS_STATUS";
export const GET_MY_EMS_FD = "GET_MY_EMS_FD";
export const SET_EMS_STATUS = "SET_EMS_STATUS";
export const CREATE_EMS_FD_DEPUTY = "CREATE_EMS_FD_DEPUTY";
export const CREATE_EMS_FD_DEPUTY_ERROR = "CREATE_EMS_FD_DEPUTY_ERROR";
export const DELETE_EMS_DEPUTY = "DELETE_EMS_DEPUTY";
export const SEARCH_MEDICAL_RECORD = "SEARCH_MEDICAL_RECORD";

export const SET_STATUS = "SET_STATUS";
export const GET_BOLOS = "GET_BOLOS";

export const CREATE_WARRANT = "CREATE_WARRANT";
export const CREATE_WARRANT_ERROR = "CREATE_WARRANT_ERROR";

export const GET_ACTIVE_UNITS = "GET_ACTIVE_UNITS";

export const CREATE_TOW_CALL = "CREATE_TOW_CALL";
export const GET_TOW_CALLS = "GET_TOW_CALLS";
export const END_TOW_CALL = "END_TOW_CALL";

export const SET_MESSAGE = "SET_MESSAGE";

export const GET_TRUCK_LOGS = "GET_TRUCK_LOGS";
export const CREATE_TRUCK_LOG = "CREATE_TRUCK_LOG";
export const CREATE_TRUCK_LOG_ERROR = "CREATE_TRUCK_LOG_ERROR";
export const DELETE_TRUCK_LOG = "DELETE_TRUCK_LOG";

export const GET_CITIZENS = "GET_CITIZENS";

/* All values */
export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";

export const GET_GENDERS = "GET_GENDERS";
export const ADD_GENDER = "ADD_GENDER";
export const DELETE_GENDER = "DELETE_GENDER";
export const UPDATE_GENDER = "UPDATE_GENDER";

export const GET_ETHNICITIES = "GET_ETHNICITIES";
export const ADD_ETHNICITY = "ADD_ETHNICITY";
export const DELETE_ETHNICITY = "DELETE_ETHNICITY";
export const UPDATE_ETHNICITY = "UPDATE_ETHNICITY";

export const GET_VEHICLES = "GET_VEHICLES";
export const ADD_VEHICLE = "ADD_VEHICLE";
export const DELETE_VEHICLE = "DELETE_VEHICLE";
export const UPDATE_VEHICLE = "UPDATE_VEHICLE";
