export enum SocketEvents {
  CheckConnection = "CHECK_CONNECTION",
  ConnectionError = "connection_error",
  ConnectionSuccess = "connection_success",
  Update911Calls = "UPDATE_911_CALLS",
  New911Call = "NEW_911_CALL",
  UpdateBolos = "UPDATE_BOLOS",
  UpdateActiveUnits = "UPDATE_ACTIVE_UNITS",
  Signal100 = "SIGNAL_100",
  PanicButton = "PANIC_BUTTON",
  UpdateAop = "UPDATE_AOP",
  UpdateAssignedUnits = "UPDATE_ASSIGNED_UNITS",
  UpdateTaxiCalls = "UPDATE_TAXI_CALLS",
  UpdateTowCalls = "UPDATE_TOW_CALLS",
  UpdateNameSearchNames = "UPDATE_NAME_SEARCH_NAMES",
}
