name: Check typescript build

on: [push, pull_request]

jobs:
  tsc-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
      - name: generate lang file
        run: npm run translation:generate
      - name: Run tsc
        run: npm run test-tsc
